name: dot_matrix_text
Description: "A Flutter plugin for creating customizable dot matrix text displays. This package allows developers to easily implement retro-style LED text effects with adjustable LED size, spacing, colors, and dynamic features such as mirror mode, flicker effects, invertible colors, and customizable board sizes. Enhance your Flutter apps with unique and visually appealing dot matrix text animations."
version: 0.1.0
homepage: https://github.com/topmoveright/dot_matrix_text

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


screenshots:
  - description: 'Example screenshot'
    path: screenshots/screenshot1.png

topics:
  - text
  - ui-components
  - dot-matrix
  - led-text

flutter:
